apiVersion: v1
kind: Service
metadata:
  name: {{ template "guestbook.fullname" . }}
  labels:
    app: {{ template "guestbook.name" . }}
spec:
  ports:
  - port: 3000
    targetPort: http-server
  selector:
    app: guestbook
  type: {{ .Values.serviceType }}
